package Interfaces;

import Conexion.Conexion;
import Conexion.FabricaConexion;
import DAO.FabricaDAO;
import Excepciones.ExcepcionRegistro;
import Objetos.ObjetoEstado;
import Objetos.ObjetoPais;
import Objetos.ObjetoSocio;
import Utilidades.EnviarCorreo;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.mail.MessagingException;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

public class Login extends javax.swing.JFrame {

    
    private FabricaDAO fabricaDAO;
    private Conexion conexion;
    private ObjetoSocio socioRegistro;
    private ArrayList<ObjetoPais> listaPaises;
    private ArrayList<ObjetoEstado> listaEstados;
    private static Login singleton = null;
    
    private Login() {
        Estilo.tema();
        initComponents();
        setResizable(false);
        setSize(570, 300);
        setLocationRelativeTo(null);
        limpiarTextFields();
        ButtonGroup grupoRadios = new ButtonGroup();
        grupoRadios.add(radioInfo);
        grupoRadios.add(radioMInfo);

        
        
        panelConectarme.setVisible(false);
        panelInfo.setVisible(false);
        panelRegistro.setVisible(false);
        panelRecuperarContrasena.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnIS = new javax.swing.JButton();
        btnRegistrarse = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        panelConectarme = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        btnConectarLogin = new javax.swing.JButton();
        btnCancelarLogin = new javax.swing.JButton();
        olvideContrasena = new javax.swing.JLabel();
        notificaciónLogin = new javax.swing.JLabel();
        txtContrasenaLogin = new javax.swing.JPasswordField();
        panelRegistro = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtNumSocio = new javax.swing.JTextField();
        btnAceptarRegistro = new javax.swing.JButton();
        btnCancelarRegistro = new javax.swing.JButton();
        avisoRegistroLogin = new javax.swing.JLabel();
        panelInfo = new javax.swing.JPanel();
        txtTelefonoInfo = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cboxPaisInfo = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        cboxEstadoInfo = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        btnCancelarInfo = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        radioMInfo = new javax.swing.JRadioButton();
        jLabel21 = new javax.swing.JLabel();
        radioInfo = new javax.swing.JRadioButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtNombreInfo = new javax.swing.JTextField();
        txtAPInfo = new javax.swing.JTextField();
        txtAMInfo = new javax.swing.JTextField();
        txtFechaNacInfo = new javax.swing.JTextField();
        txtDireccionInfo = new javax.swing.JTextField();
        txtContrasenaInfo = new javax.swing.JPasswordField();
        txtRepContrasenaInfo = new javax.swing.JPasswordField();
        txtCorreoInfo = new javax.swing.JTextField();
        btnGuardarInfo = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        avisoRegistro = new javax.swing.JLabel();
        panelRecuperarContrasena = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCorreoRecuperar = new javax.swing.JTextField();
        btnEnviarRecuperar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        btnCancelarRecuperar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo_nutrilitePNG.png"))); // NOI18N
        jLabel1.setText("Logo");

        btnIS.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnIS.setText("Iniciar Sesión");
        btnIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnISActionPerformed(evt);
            }
        });

        btnRegistrarse.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnRegistrarse.setText("Registrarse");
        btnRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarseActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Texto sobre los desarrolladores");

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPrincipalLayout.createSequentialGroup()
                                .addComponent(btnIS, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(btnRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelPrincipalLayout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(jLabel2)))))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIS, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        panelConectarme.setPreferredSize(new java.awt.Dimension(570, 400));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo_nutrilitePNG.png"))); // NOI18N
        jLabel27.setText("Logo");

        jLabel28.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel28.setText("Usuario:");

        txtUsuario.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel29.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel29.setText("Contraseña: ");

        btnConectarLogin.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnConectarLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iniciarsesion.png"))); // NOI18N
        btnConectarLogin.setText("Conectar");
        btnConectarLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConectarLoginActionPerformed(evt);
            }
        });

        btnCancelarLogin.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnCancelarLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/clear.png"))); // NOI18N
        btnCancelarLogin.setText("Cancelar");
        btnCancelarLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarLoginActionPerformed(evt);
            }
        });

        olvideContrasena.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        olvideContrasena.setText("Olvidé mi contraseña.");
        olvideContrasena.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                olvideContrasenaMouseClicked(evt);
            }
        });

        notificaciónLogin.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        notificaciónLogin.setForeground(new java.awt.Color(204, 0, 0));
        notificaciónLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        notificaciónLogin.setText("Jlabel");
        notificaciónLogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txtContrasenaLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContrasenaLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelConectarmeLayout = new javax.swing.GroupLayout(panelConectarme);
        panelConectarme.setLayout(panelConectarmeLayout);
        panelConectarmeLayout.setHorizontalGroup(
            panelConectarmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConectarmeLayout.createSequentialGroup()
                .addGroup(panelConectarmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelConectarmeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelConectarmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(panelConectarmeLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(notificaciónLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelConectarmeLayout.createSequentialGroup()
                            .addGap(66, 66, 66)
                            .addGroup(panelConectarmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel28)
                                .addComponent(jLabel29))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(panelConectarmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                                .addComponent(txtContrasenaLogin)))))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelConectarmeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panelConectarmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelConectarmeLayout.createSequentialGroup()
                        .addComponent(btnConectarLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(btnCancelarLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelConectarmeLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(olvideContrasena)))
                .addGap(148, 148, 148))
        );
        panelConectarmeLayout.setVerticalGroup(
            panelConectarmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConectarmeLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(panelConectarmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel28)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelConectarmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(txtContrasenaLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(notificaciónLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelConectarmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConectarLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelarLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(olvideContrasena)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Número de Socio:");

        txtNumSocio.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtNumSocio.setText("txtNumSocio");
        txtNumSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumSocioActionPerformed(evt);
            }
        });

        btnAceptarRegistro.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnAceptarRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tick.png"))); // NOI18N
        btnAceptarRegistro.setText("Aceptar");
        btnAceptarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarRegistroActionPerformed(evt);
            }
        });

        btnCancelarRegistro.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnCancelarRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/clear.png"))); // NOI18N
        btnCancelarRegistro.setText("Cancelar");
        btnCancelarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarRegistroActionPerformed(evt);
            }
        });

        avisoRegistroLogin.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        avisoRegistroLogin.setForeground(new java.awt.Color(204, 0, 0));
        avisoRegistroLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        avisoRegistroLogin.setText("Jlabel");
        avisoRegistroLogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelRegistroLayout = new javax.swing.GroupLayout(panelRegistro);
        panelRegistro.setLayout(panelRegistroLayout);
        panelRegistroLayout.setHorizontalGroup(
            panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegistroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAceptarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(162, 162, 162))
            .addGroup(panelRegistroLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(avisoRegistroLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelRegistroLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtNumSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        panelRegistroLayout.setVerticalGroup(
            panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistroLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNumSocio, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(avisoRegistroLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelInfo.setPreferredSize(new java.awt.Dimension(770, 450));

        txtTelefonoInfo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtTelefonoInfo.setText("Telefono");

        jLabel25.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel25.setText("*Sexo: ");

        jLabel26.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel26.setText("*Teléfono: ");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("*Pais:");

        cboxPaisInfo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cboxPaisInfo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione pais" }));
        cboxPaisInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxPaisInfoActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel17.setText("*Nombre: ");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("*Estado:");

        jLabel18.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel18.setText("*Apellido Paterno: ");

        cboxEstadoInfo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cboxEstadoInfo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione estado" }));

        jLabel19.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel19.setText("Apellido Materno: ");

        btnCancelarInfo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnCancelarInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/clear.png"))); // NOI18N
        btnCancelarInfo.setText("Cancelar");
        btnCancelarInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarInfoActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel20.setText("*Fecha de Nacimiento: ");

        radioMInfo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        radioMInfo.setText("Maculino");

        jLabel21.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel21.setText("*Dirección: ");

        radioInfo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        radioInfo.setText("Femenino");

        jLabel22.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel22.setText("*Contraseña: ");

        jLabel23.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel23.setText("*Repetir Contraseña: ");

        jLabel24.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel24.setText("*Correo electrónico: ");

        txtNombreInfo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtNombreInfo.setText("Nombre");

        txtAPInfo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtAPInfo.setText("APellido paterno");

        txtAMInfo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtAMInfo.setText("Apellido MAterno");

        txtFechaNacInfo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtFechaNacInfo.setText("FEcha Nac");

        txtDireccionInfo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtDireccionInfo.setText("Direccion");

        txtContrasenaInfo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtContrasenaInfo.setText("Contraseña");

        txtRepContrasenaInfo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtRepContrasenaInfo.setText("jPasswordField2");

        txtCorreoInfo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtCorreoInfo.setText("Correo");

        btnGuardarInfo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnGuardarInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/guardar.png"))); // NOI18N
        btnGuardarInfo.setText("Guardar");
        btnGuardarInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarInfoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("DD/MM/AAAA");

        avisoRegistro.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        avisoRegistro.setForeground(new java.awt.Color(204, 0, 0));
        avisoRegistro.setText("jLabel7");

        javax.swing.GroupLayout panelInfoLayout = new javax.swing.GroupLayout(panelInfo);
        panelInfo.setLayout(panelInfoLayout);
        panelInfoLayout.setHorizontalGroup(
            panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInfoLayout.createSequentialGroup()
                        .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelInfoLayout.createSequentialGroup()
                                .addGap(139, 139, 139)
                                .addComponent(radioMInfo)
                                .addGap(18, 18, 18)
                                .addComponent(radioInfo))
                            .addComponent(jLabel25))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(cboxPaisInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(cboxEstadoInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(133, 133, 133))
                    .addGroup(panelInfoLayout.createSequentialGroup()
                        .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelInfoLayout.createSequentialGroup()
                                .addGap(291, 291, 291)
                                .addComponent(btnGuardarInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancelarInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelInfoLayout.createSequentialGroup()
                                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18))
                                .addGap(18, 18, 18)
                                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelInfoLayout.createSequentialGroup()
                                        .addComponent(txtFechaNacInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6))
                                    .addGroup(panelInfoLayout.createSequentialGroup()
                                        .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtAPInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                                            .addComponent(txtNombreInfo))
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel19)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtAMInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(panelInfoLayout.createSequentialGroup()
                                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel24))
                                .addGap(23, 23, 23)
                                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtRepContrasenaInfo, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtContrasenaInfo, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCorreoInfo, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDireccionInfo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE))
                                .addGap(40, 40, 40)
                                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelInfoLayout.createSequentialGroup()
                                        .addComponent(jLabel26)
                                        .addGap(13, 13, 13)
                                        .addComponent(txtTelefonoInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(avisoRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(121, 121, 121))))
        );
        panelInfoLayout.setVerticalGroup(
            panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtNombreInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtAPInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(txtAMInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtFechaNacInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelInfoLayout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(5, 5, 5))
                    .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTelefonoInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26))
                        .addComponent(txtDireccionInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16)
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCorreoInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txtContrasenaInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtRepContrasenaInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(avisoRegistro))
                .addGap(18, 18, 18)
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(radioMInfo)
                    .addComponent(radioInfo)
                    .addComponent(jLabel4)
                    .addComponent(cboxPaisInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(cboxEstadoInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelarInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Recuperar contraseña");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setText("Correo electronico");

        txtCorreoRecuperar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtCorreoRecuperar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoRecuperarActionPerformed(evt);
            }
        });

        btnEnviarRecuperar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnEnviarRecuperar.setText("Enviar");
        btnEnviarRecuperar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarRecuperarActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(0, 153, 0));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/email.png"))); // NOI18N

        btnCancelarRecuperar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnCancelarRecuperar.setText("Cancelar");
        btnCancelarRecuperar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarRecuperarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRecuperarContrasenaLayout = new javax.swing.GroupLayout(panelRecuperarContrasena);
        panelRecuperarContrasena.setLayout(panelRecuperarContrasenaLayout);
        panelRecuperarContrasenaLayout.setHorizontalGroup(
            panelRecuperarContrasenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(panelRecuperarContrasenaLayout.createSequentialGroup()
                .addGroup(panelRecuperarContrasenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRecuperarContrasenaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7))
                    .addGroup(panelRecuperarContrasenaLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(panelRecuperarContrasenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelRecuperarContrasenaLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCorreoRecuperar, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRecuperarContrasenaLayout.createSequentialGroup()
                                .addGap(131, 131, 131)
                                .addComponent(jLabel8)
                                .addGap(124, 124, 124)))))
                .addContainerGap(119, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRecuperarContrasenaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnEnviarRecuperar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnCancelarRecuperar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(159, 159, 159))
        );
        panelRecuperarContrasenaLayout.setVerticalGroup(
            panelRecuperarContrasenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRecuperarContrasenaLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(panelRecuperarContrasenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(txtCorreoRecuperar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelRecuperarContrasenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCancelarRecuperar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEnviarRecuperar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelConectarme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelRecuperarContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 67, Short.MAX_VALUE)
                    .addComponent(panelConectarme, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 67, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 198, Short.MAX_VALUE)
                    .addComponent(panelRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 199, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelRecuperarContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnISActionPerformed
        panelPrincipal.setVisible(false);
        panelConectarme.setVisible(true);
        setSize(570, 370);
        setLocationRelativeTo(null);
    }//GEN-LAST:event_btnISActionPerformed

    private void btnRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarseActionPerformed
        // TODO add your handling code here:
        panelPrincipal.setVisible(false);
        panelRegistro.setVisible(true);
        txtNumSocio.setText("");
        setSize(570, 200);
        setLocationRelativeTo(null);

    }//GEN-LAST:event_btnRegistrarseActionPerformed

    private void btnConectarLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConectarLoginActionPerformed
        try {
            conectarMySQL();
            String user = txtUsuario.getText();
            String password = txtContrasenaLogin.getText();
            if (!user.equals(password)) {
                ObjetoSocio socio = fabricaDAO.getSocioDAO().login(Integer.parseInt(user), password);
                if (socio != null){
                    Administrador.correr(socio, fabricaDAO, conexion);
                    this.setVisible(false);
                } else
                    notificaciónLogin.setText("El numero de socio no existe o no se ha dado de alta");
            } else
                notificaciónLogin.setText("Numero de socio y/o contraseña incorrecta");
        } catch (SQLException e) {
            notificaciónLogin.setText("Error de conexion");
            int confirmacion = JOptionPane.showConfirmDialog(this, "Hubo un error al realizar la conexion.\n¿Desea acceder de manera local?",
                    "Error de conexion", JOptionPane.YES_NO_OPTION);
            if (confirmacion == JOptionPane.YES_OPTION) {
                try {
                    conectarHSQL();
                    crearTablasHSQL();
                    String user = txtUsuario.getText();
                    String password = txtContrasenaLogin.getText();
                    if (!user.equals(password)) {
                        ObjetoSocio socio = fabricaDAO.getSocioDAO().login(Integer.parseInt(user), password);
                        if (socio != null) {
                            Administrador admin = new Administrador(socio, fabricaDAO, conexion);
                            admin.setVisible(true);
                            admin.setAdminVisible(false);
                            admin.setDescargarEneable(false);
                            this.setVisible(false);
                        } else {
                            notificaciónLogin.setText("El numero de socio no existe o no se ha dado de alta");
                        }
                    } else {
                        notificaciónLogin.setText("Numero de socio y/o contraseña incorrecta");
                    }
                } catch (SQLException ex) {
                    System.out.println("error de conexion en HSQL");
                    e.printStackTrace();
                } catch (ClassNotFoundException ex) {
                    notificaciónLogin.setText("Error en la conexion: No Driver");
                } catch (NumberFormatException ex) {
                    notificaciónLogin.setText("Numero de socio invalido");
                }
            }
        } catch (NumberFormatException e){
            notificaciónLogin.setText("Numero de socio invalido");
        } catch (ClassNotFoundException e){
            notificaciónLogin.setText("Error en la conexion: No Driver");
        }
    }//GEN-LAST:event_btnConectarLoginActionPerformed

    private void btnCancelarLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarLoginActionPerformed
        panelConectarme.setVisible(false);
        notificaciónLogin.setText("");
        txtUsuario.setText("");
        txtContrasenaLogin.setText("");
        panelPrincipal.setVisible(true);
        setLocationRelativeTo(null);
        setSize(570, 300);
    }//GEN-LAST:event_btnCancelarLoginActionPerformed

    private void btnAceptarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarRegistroActionPerformed
        socioRegistro = null;
        try {
            conectarMySQL();
            String id = txtNumSocio.getText();
            socioRegistro = fabricaDAO.getSocioDAO().login(Integer.parseInt(id), id);
            if (socioRegistro != null) {
                panelInfo.setVisible(true);
                setSize(770, 470);
                setLocationRelativeTo(null);
                txtNumSocio.setText("");
                avisoRegistroLogin.setText("");
                panelRegistro.setVisible(false);
                listaPaises = fabricaDAO.getPaisDAO().verPaisesPorNombre();
                for (ObjetoPais pais : listaPaises) {
                    cboxPaisInfo.addItem(pais.getNombre());
                }
            } else 
                avisoRegistroLogin.setText("El numero de socio no es valido o no se ha dado de alta");
        } catch (SQLException e) {
            avisoRegistroLogin.setText("Error de conexion");
        } catch (NumberFormatException e) {
            avisoRegistroLogin.setText("Numero de socio no válido");
        } catch (ClassNotFoundException e) {
            System.out.println("Error en la conexion: No Driver");
        }
    }//GEN-LAST:event_btnAceptarRegistroActionPerformed

    private void btnCancelarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarRegistroActionPerformed
        panelRegistro.setVisible(false);
        panelPrincipal.setVisible(true);
        txtNumSocio.setText("");
        avisoRegistroLogin.setText("");
        setSize(570, 300);
        setLocationRelativeTo(null);
    }//GEN-LAST:event_btnCancelarRegistroActionPerformed

    private void btnCancelarInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarInfoActionPerformed
        panelInfo.setVisible(false);
        panelRegistro.setVisible(true);
        setSize(570, 200);
        setLocationRelativeTo(null);
    }//GEN-LAST:event_btnCancelarInfoActionPerformed

    private void olvideContrasenaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_olvideContrasenaMouseClicked
        panelConectarme.setVisible(false);
        panelRecuperarContrasena.setVisible(true);
        setSize(570, 230);
        setLocationRelativeTo(null);
    }//GEN-LAST:event_olvideContrasenaMouseClicked

    private void btnGuardarInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarInfoActionPerformed
        try {
            validarRegistro();
            guardarRegistro();
            fabricaDAO.getSocioDAO().modificarSocio(socioRegistro);
            panelInfo.setVisible(false);
            limpiarTextFields();
            JOptionPane.showMessageDialog(this, "Registro exitoso");
            panelPrincipal.setVisible(true);
            setSize(570, 300);
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error de conexion");
            panelInfo.setVisible(false);
            limpiarTextFields();
            panelRegistro.setVisible(true);
        } catch (ExcepcionRegistro e) {
            avisoRegistro.setText(e.getMessage());
        }
    }//GEN-LAST:event_btnGuardarInfoActionPerformed

    private void cboxPaisInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxPaisInfoActionPerformed
        int index = cboxPaisInfo.getSelectedIndex();
        try {
            listaEstados = fabricaDAO.getEstadoDAO().verEstadosPorPais(listaPaises.get(index-1).getId());
            cboxEstadoInfo.setModel(new DefaultComboBoxModel(new String[] {"Seleccione Estado"}));
            for (ObjetoEstado estado : listaEstados) {
                cboxEstadoInfo.addItem(estado.getNombre());
            }
        } catch (SQLException e) {
            System.out.println("Error en cargar los estados. (cboxPaisInfoActionPerformed)");
            e.printStackTrace();
        } catch (IndexOutOfBoundsException e) {
            cboxEstadoInfo.setModel(new DefaultComboBoxModel(new String[] {"Seleccione Estado"}));
        }
    }//GEN-LAST:event_cboxPaisInfoActionPerformed

    private void btnCancelarRecuperarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarRecuperarActionPerformed
        panelConectarme.setVisible(true);
        panelRecuperarContrasena.setVisible(false);
        setSize(570, 360);
        setLocationRelativeTo(null);
    }//GEN-LAST:event_btnCancelarRecuperarActionPerformed

    private void txtNumSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumSocioActionPerformed
        btnAceptarRegistroActionPerformed(evt);
    }//GEN-LAST:event_txtNumSocioActionPerformed

    private void btnEnviarRecuperarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarRecuperarActionPerformed
        
        try {
            conectarMySQL();
            String correoDestino = txtCorreoRecuperar.getText();
            String password = fabricaDAO.getSocioDAO().verContraseña(correoDestino);
            if (password == null) 
                JOptionPane.showMessageDialog(this, "Correo electronico no valido");
            else {
                EnviarCorreo.sendMessage(correoDestino, password);
                JOptionPane.showMessageDialog(this, "Su contraseña ha sido enviada");
                panelConectarme.setVisible(true);
                panelRecuperarContrasena.setVisible(false);
                setSize(570, 360);
                setLocationRelativeTo(null);
            }
        } catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(this, "Error de conexion: No Driver");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error de conexion");
        } catch (MessagingException e) {
            JOptionPane.showMessageDialog(this, "No ha sido posible enviar el correo");
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_btnEnviarRecuperarActionPerformed

    private void txtCorreoRecuperarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoRecuperarActionPerformed
        btnEnviarRecuperarActionPerformed(evt);
    }//GEN-LAST:event_txtCorreoRecuperarActionPerformed

    private void txtContrasenaLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContrasenaLoginActionPerformed
        btnConectarLoginActionPerformed(evt);
    }//GEN-LAST:event_txtContrasenaLoginActionPerformed

    private static Login getInstance() {
        singleton = new Login();
        return singleton;
    }
    
    private void limpiarTextFields() {
        txtNombreInfo.setText("");
        txtAPInfo.setText("");
        txtAMInfo.setText("");
        txtFechaNacInfo.setText("");
        txtDireccionInfo.setText("");
        txtCorreoInfo.setText("");
        txtContrasenaInfo.setText("");
        txtRepContrasenaInfo.setText("");
        txtTelefonoInfo.setText("");
        radioInfo.setSelected(false);
        radioMInfo.setSelected(false);
        cboxPaisInfo.setModel(new DefaultComboBoxModel(new String[] {"Seleccione Pais"}));
        cboxEstadoInfo.setModel(new DefaultComboBoxModel(new String[] {"Seleccione Estado"}));
        avisoRegistro.setText("");
        avisoRegistroLogin.setText("");
        notificaciónLogin.setText("");
    }
    
    private void validarRegistro() throws ExcepcionRegistro, SQLException {
        if (txtNombreInfo.getText().equals(""))
            throw new ExcepcionRegistro("Escriba un nombre");
        if (txtAPInfo.getText().equals(""))
            throw new ExcepcionRegistro("Escriba su apellido");
        if (txtFechaNacInfo.getText().length() != 10)
            throw new ExcepcionRegistro("Fecha de nacimiento invalida");
        if (txtDireccionInfo.getText().equals(""))
            throw new ExcepcionRegistro("Escriba una direccion valida");
        if (txtCorreoInfo.getText().equals(""))
            throw new ExcepcionRegistro("Escriba una direccion de correo valida");
        if (fabricaDAO.getSocioDAO().existeCorreo(txtCorreoInfo.getText()) != 0)
            throw new ExcepcionRegistro("Esta direccion de correo ya esta ligada a otro socio");
        if (txtTelefonoInfo.getText().equals(""))
            throw new ExcepcionRegistro("Escriba un telefono valido");
        if (txtContrasenaInfo.getText().equals(""))
            throw new ExcepcionRegistro("Escriba una contrasena");
        if (!txtContrasenaInfo.getText().equals(txtRepContrasenaInfo.getText()))
            throw new ExcepcionRegistro("Las contrasenas no coinciden");
        if (txtContrasenaInfo.getText().length() < 8)
            throw new ExcepcionRegistro("La contrasena es muy corta");
        if ((!radioInfo.isSelected()) && (!radioMInfo.isSelected()))
            throw new ExcepcionRegistro("Seleccione su sexo");
        if (cboxPaisInfo.getSelectedIndex() == 0)
            throw new ExcepcionRegistro("Seleccione un pais");
        if (cboxEstadoInfo.getSelectedIndex() == 0)
            throw new ExcepcionRegistro("Seleccione un estado");
    }
    
    private void guardarRegistro(){
        socioRegistro.setNombre(txtNombreInfo.getText());
        socioRegistro.setApellidoPaterno(txtAPInfo.getText());
        socioRegistro.setApellidoMaterno(txtAMInfo.getText());
        socioRegistro.setNombreCompleto();
        socioRegistro.setFechaNacimiento(txtFechaNacInfo.getText());
        socioRegistro.setDireccion(txtDireccionInfo.getText());
        socioRegistro.setCorreo(txtCorreoInfo.getText());
        socioRegistro.setPassword(txtContrasenaInfo.getText());
        socioRegistro.setTelefono(txtTelefonoInfo.getText());
        if (radioInfo.isSelected())
            socioRegistro.setSexo("F");
        else
            socioRegistro.setSexo("M");
        int index = cboxEstadoInfo.getSelectedIndex() - 1;
        socioRegistro.setIdEstado(listaEstados.get(index).getId());
    }
    
    private void conectarMySQL() throws SQLException, ClassNotFoundException {
        conexion = FabricaConexion.getConexionMySQL();
        fabricaDAO = new FabricaDAO(conexion);
    }
    
    private void conectarHSQL() throws SQLException, ClassNotFoundException {
        conexion = FabricaConexion.getConexionHSQL();
        fabricaDAO = new FabricaDAO(conexion);
    }
    
    private void crearTablasHSQL() {
        try {
            fabricaDAO.getEstuturaDAO().crearTablas();
            System.out.println("Tablas creadas");
            fabricaDAO.getEstuturaDAO().crearRelaciones();
            System.out.println("Relaciones creadas");
        } catch (SQLException e) {
            System.out.println("Las tablas y/o relaciones ya existen");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
//                Estilo.tema(this);
                getInstance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avisoRegistro;
    private javax.swing.JLabel avisoRegistroLogin;
    private javax.swing.JButton btnAceptarRegistro;
    private javax.swing.JButton btnCancelarInfo;
    private javax.swing.JButton btnCancelarLogin;
    private javax.swing.JButton btnCancelarRecuperar;
    private javax.swing.JButton btnCancelarRegistro;
    private javax.swing.JButton btnConectarLogin;
    private javax.swing.JButton btnEnviarRecuperar;
    private javax.swing.JButton btnGuardarInfo;
    private javax.swing.JButton btnIS;
    private javax.swing.JButton btnRegistrarse;
    private javax.swing.JComboBox cboxEstadoInfo;
    private javax.swing.JComboBox cboxPaisInfo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel notificaciónLogin;
    private javax.swing.JLabel olvideContrasena;
    private javax.swing.JPanel panelConectarme;
    private javax.swing.JPanel panelInfo;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelRecuperarContrasena;
    private javax.swing.JPanel panelRegistro;
    private javax.swing.JRadioButton radioInfo;
    private javax.swing.JRadioButton radioMInfo;
    private javax.swing.JTextField txtAMInfo;
    private javax.swing.JTextField txtAPInfo;
    private javax.swing.JPasswordField txtContrasenaInfo;
    private javax.swing.JPasswordField txtContrasenaLogin;
    private javax.swing.JTextField txtCorreoInfo;
    private javax.swing.JTextField txtCorreoRecuperar;
    private javax.swing.JTextField txtDireccionInfo;
    private javax.swing.JTextField txtFechaNacInfo;
    private javax.swing.JTextField txtNombreInfo;
    private javax.swing.JTextField txtNumSocio;
    private javax.swing.JPasswordField txtRepContrasenaInfo;
    private javax.swing.JTextField txtTelefonoInfo;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
